services:
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - bitcoin_network
    restart: unless-stopped

  collector:
    image: asia-northeast3-docker.pkg.dev/poised-standard-484213-a7/bitcoin-pipeline/collector:latest
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./keys/gcp-key.json:/keys/gcp-key.json:ro
    networks:
      - bitcoin_network
    restart: unless-stopped

  processor:
    image: asia-northeast3-docker.pkg.dev/poised-standard-484213-a7/bitcoin-pipeline/processor:latest
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./keys/gcp-key.json:/keys/gcp-key.json:ro
    networks:
      - bitcoin_network
    restart: unless-stopped

networks:
  bitcoin_network:
    driver: bridge