services:
  redis:
    image: redis:7-alpine
    container_name: bitcoin_redis
    ports:
      - "6379:6379"
    networks:
      - bitcoin_network

  collector:
    image: asia-northeast3-docker.pkg.dev/poised-standard-484213-a7/bitcoin-pipeline/collector:latest
    container_name: bitcoin_collector
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./keys/gcp-key.json:/keys/gcp-key.json:ro
    networks:
      - bitcoin_network
    restart: unless-stopped

  processor:
    image: asia-northeast3-docker.pkg.dev/poised-standard-484213-a7/bitcoin-pipeline/processor:latest
    container_name: bitcoin_processor
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./keys/gcp-key.json:/keys/gcp-key.json:ro
    networks:
      - bitcoin_network

networks:
  bitcoin_network:
    driver: bridge